# Generated by Django 4.1 on 2023-04-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='todo_task_title_b44c65_idx'),
        ),
    ]
